config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  controller :sessions do

    get 'login' => :new

    post 'login' => :create

    delete 'logout' => :destroy

  end
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

   get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :products
  root 'store#index'
  #root "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true

  belongs_to :cart

  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: [:index, :show, :new, :create]
  include CurrentCart
	before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
     product = Product.find(params[:product_id])
     @line_item = @cart.add_product(product)
 
     respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        #format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
    #  params.require(:line_item).permit(:product_id, :cart_id)
    params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(line_item) do |f| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_id %>
    <%= f.text_field :product_id , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cart_id %>
    <%= f.text_field :cart_id , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :create, class:"btn btn-default"%>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item , class:"btn btn-xs btn-default" %> |
<%= link_to 'Back', line_items_path , class:"btn btn-xs btn-default"  %>

app/views/line_items/index.html.erb
<p id="notice" class="w3-panel"><%= notice %></p>

<h1>Line Items</h1>

<table class="w3-table-all">
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item , class:"w3-button w3-light-gray w3-border" %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) , class:"w3-button w3-light-gray w3-border" %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } , class:"w3-button w3-light-gray w3-border" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path , class:"w3-button w3-light-gray" %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path , class:"btn btn-xs btn-danger" %>

app/views/line_items/show.html.erb
<p id="notice" class="w3-panel"><%= notice %></p>

<div class="w3-panel w3-aqua">

<table class="w3-table-all">
<thead>
  <tr>
    <th><h1>line_item</h1></th>
    <th></th>
  </tr>
</thead>
<tbody>
<tr>

<td>
  <strong>Product:</strong>
</td>
<td>
  <%= @line_item.product %>
</td>
</tr>

<td>
  <strong>Cart:</strong>
</td>
<td>
  <%= @line_item.cart %>
</td>
</tr>


<tr>
<td>
<%= link_to 'Edit', edit_line_item_path(@line_item) ,class:"w3-button w3-light-gray w3-border" %> 
</td>
<td>
<%= link_to 'Back', line_items_path , class:"w3-button w3-light-gray w3-border" %>
</td>
</tr>
</tbody>
</table>
</div>